<?php

$ranksetNames['mario'] = 'Mario';

$ranksetData['mario'] = [
    ['num' => 0, 'image' => '', 'text' => 'Non-poster'],
    ['num' => 1, 'image' => '', 'text' => 'Newcomer'],
    ['num' => 5, 'image' => 'microgoomba.png', 'text' => 'Micro-Goomba'],
    ['num' => 10, 'image' => 'goomba.png', 'text' => 'Goomba'],
    ['num' => 20, 'image' => 'redgoomba.png', 'text' => 'Red Goomba'],
    ['num' => 30, 'image' => 'paragoomba.png', 'text' => 'Paragoomba'],
    ['num' => 40, 'image' => 'redparagoomba.png', 'text' => 'Red Paragoomba'],
    ['num' => 50, 'image' => 'shyguy.png', 'text' => 'Shyguy'],
    ['num' => 80, 'image' => 'koopa.png', 'text' => 'Koopa'],
    ['num' => 120, 'image' => 'redkoopa.png', 'text' => 'Red Koopa'],
    ['num' => 140, 'image' => 'paratroopa.png', 'text' => 'Paratroopa'],
    ['num' => 160, 'image' => 'redparatroopa.png', 'text' => 'Red Paratroopa'],
    ['num' => 180, 'image' => 'cheepcheep.png', 'text' => 'Cheep-cheep'],
    ['num' => 200, 'image' => 'redcheepcheep.png', 'text' => 'Red Cheep-cheep'],
    ['num' => 225, 'image' => 'ninji.png', 'text' => 'Ninji'],
    ['num' => 250, 'image' => 'flurry.png', 'text' => 'Flurry'],
    ['num' => 275, 'image' => 'snifit.png', 'text' => 'Snifit'],
    ['num' => 300, 'image' => 'porcupo.png', 'text' => 'Porcupo'],
    ['num' => 325, 'image' => 'panser.png', 'text' => 'Panser'],
    ['num' => 350, 'image' => 'mole.png', 'text' => 'Mole'],
    ['num' => 375, 'image' => 'buzzybeetle.png', 'text' => 'Buzzy Beetle'],
    ['num' => 400, 'image' => 'nipperplant.png', 'text' => 'Nipper Plant'],
    ['num' => 425, 'image' => 'bloober.png', 'text' => 'Bloober'],
    ['num' => 450, 'image' => 'busterbeetle.png', 'text' => 'Buster Beetle'],
    ['num' => 475, 'image' => 'beezo.png', 'text' => 'Beezo'],
    ['num' => 500, 'image' => 'bulletbill.png', 'text' => 'Bullet Bill'],
    ['num' => 525, 'image' => 'rex.png', 'text' => 'Rex'],
    ['num' => 550, 'image' => 'lakitu.png', 'text' => 'Lakitu'],
    ['num' => 575, 'image' => 'spiny.png', 'text' => 'Spiny'],
    ['num' => 600, 'image' => 'bobomb.png', 'text' => 'Bob-Omb'],
    ['num' => 625, 'image' => 'drybones.png', 'text' => 'Dry Bones'],
    ['num' => 650, 'image' => 'cobrat.png', 'text' => 'Cobrat'],
    ['num' => 675, 'image' => 'pokey.png', 'text' => 'Pokey'],
    ['num' => 700, 'image' => 'spike.png', 'text' => 'Spike'],
    ['num' => 725, 'image' => 'melonbug.png', 'text' => 'Melon Bug'],
    ['num' => 750, 'image' => 'lanternghost.png', 'text' => 'Lantern Ghost'],
    ['num' => 775, 'image' => 'fuzzy.png', 'text' => 'Fuzzy'],
    ['num' => 800, 'image' => 'bandit.png', 'text' => 'Bandit'],
    ['num' => 830, 'image' => 'superkoopa.png', 'text' => 'Super Koopa'],
    ['num' => 860, 'image' => 'redsuperkoopa.png', 'text' => 'Red Super Koopa'],
    ['num' => 900, 'image' => 'boo.png', 'text' => 'Boo'],
    ['num' => 950, 'image' => 'fuzzball.png', 'text' => 'Fuzz Ball'],
    ['num' => 1000, 'image' => 'boomerangbrother.png', 'text' => 'Boomerang Brother'],
    ['num' => 1050, 'image' => 'hammerbrother.png', 'text' => 'Hammer Brother'],
    ['num' => 1100, 'image' => 'firebrother.png', 'text' => 'Fire Brother'],
    ['num' => 1150, 'image' => 'firesnake.png', 'text' => 'Fire Snake'],
    ['num' => 1200, 'image' => 'giantgoomba.png', 'text' => 'Giant Goomba'],
    ['num' => 1250, 'image' => 'giantkoopa.png', 'text' => 'Giant Koopa'],
    ['num' => 1300, 'image' => 'giantredkoopa.png', 'text' => 'Giant Red Koopa'],
    ['num' => 1350, 'image' => 'giantparatroopa.png', 'text' => 'Giant Paratroopa'],
    ['num' => 1400, 'image' => 'giantredparatroopa.png', 'text' => 'Giant Red Paratroopa'],
    ['num' => 1450, 'image' => 'chuck.png', 'text' => 'Chuck'],
    ['num' => 1500, 'image' => 'thwomp.png', 'text' => 'Thwomp'],
    ['num' => 1550, 'image' => 'bossbass.png', 'text' => 'Boss Bass'],
    ['num' => 1600, 'image' => 'volcanolotus.png', 'text' => 'Volcano Lotus'],
    ['num' => 1650, 'image' => 'lavalotus.png', 'text' => 'Lava Lotus'],
    ['num' => 1700, 'image' => 'ptooie.png', 'text' => 'Ptooie'],
    ['num' => 1800, 'image' => 'sledgebrother.png', 'text' => 'Sledge Brother'],
    ['num' => 1900, 'image' => 'boomboom.png', 'text' => 'Boomboom'],
    ['num' => 2000, 'image' => 'birdo.png', 'text' => 'Birdo'],
    ['num' => 2100, 'image' => 'redbirdo.png', 'text' => 'Red Birdo'],
    ['num' => 2200, 'image' => 'greenbirdo.png', 'text' => 'Green Birdo'],
    ['num' => 2300, 'image' => 'larrykoopa.png', 'text' => 'Larry Koopa'],
    ['num' => 2400, 'image' => 'mortonkoopa.png', 'text' => 'Morton Koopa'],
    ['num' => 2500, 'image' => 'wendykoopa.png', 'text' => 'Wendy Koopa'],
    ['num' => 2600, 'image' => 'iggykoopa.png', 'text' => 'Iggy Koopa'],
    ['num' => 2700, 'image' => 'roykoopa.png', 'text' => 'Roy Koopa'],
    ['num' => 2800, 'image' => 'lemmykoopa.png', 'text' => 'Lemmy Koopa'],
    ['num' => 2900, 'image' => 'ludwigvonkoopa.png', 'text' => 'Ludwig Von Koopa'],
    ['num' => 3000, 'image' => 'triclyde.png', 'text' => 'Triclyde'],
    ['num' => 3100, 'image' => 'magikoopa.png', 'text' => 'Magikoopa'],
    ['num' => 3200, 'image' => 'wart.png', 'text' => 'Wart'],
    ['num' => 3300, 'image' => 'babybowser.png', 'text' => 'Baby Bowser'],
    ['num' => 3400, 'image' => 'kingbowserkoopa.png', 'text' => 'King Bowser Koopa'],
    ['num' => 3500, 'image' => 'yoshi.png', 'text' => 'Yoshi'],
    ['num' => 3600, 'image' => 'babyluigi.gif', 'text' => 'Baby Luigi'],
    ['num' => 3800, 'image' => 'babymario.png', 'text' => 'Baby Mario'],
    ['num' => 4000, 'image' => 'luigi.png', 'text' => 'Luigi'],
    ['num' => 4200, 'image' => 'mario.png', 'text' => 'Mario'],
    ['num' => 4300, 'image' => 'superluigi.png', 'text' => 'Super Luigi'],
    ['num' => 4400, 'image' => 'supermario.png', 'text' => 'Super Mario'],
    ['num' => 4500, 'image' => 'fireluigi.png', 'text' => 'Fire Luigi'],
    ['num' => 4600, 'image' => 'firemario.png', 'text' => 'Fire Mario'],
    ['num' => 4700, 'image' => 'capeluigi.png', 'text' => 'Cape Luigi'],
    ['num' => 4800, 'image' => 'capemario.png', 'text' => 'Cape Mario'],
    ['num' => 4900, 'image' => 'starluigi.png', 'text' => 'Star Luigi'],
    ['num' => 5000, 'image' => 'starmario.png', 'text' => 'Star Mario'],
];
