<?php

$ranksetNames['NSMBW'] = __('Newer SMBW');

$ranksetData['NSMBW'] = [
    ['num' => 0, 'image' => '', 'text' => 'Non-poster'],
    ['num' => 1, 'image' => '', 'text' => 'Newcomer'],
    ['num' => 10, 'image' => 'microgoomba.png', 'text' => 'Micro Goomba'],
    ['num' => 20, 'image' => 'goomba.png', 'text' => 'Goomba'],
    ['num' => 35, 'image' => 'paragoomba.png', 'text' => 'Paragoomba'],
    ['num' => 50, 'image' => 'chestnut_goomba.png', 'text' => 'Chestnut Goomba'],
    ['num' => 65, 'image' => 'giantgoomba.png', 'text' => 'Giant Goomba'],
    ['num' => 80, 'image' => 'koopa_green_shell.png', 'text' => 'Green Shell'],
    ['num' => 100, 'image' => 'koopa_red_shell.png', 'text' => 'Red Shell'],
    ['num' => 110, 'image' => 'koopa_green.png', 'text' => 'Koopa Troopa'],
    ['num' => 120, 'image' => 'koopa_red.png', 'text' => 'Red Koopa Troopa'],
    ['num' => 140, 'image' => 'fencekoopa_vert.png', 'text' => 'Fence Koopa'],
    ['num' => 160, 'image' => 'mechakoopa.png', 'text' => 'Mecha Koopa'],
    ['num' => 180, 'image' => 'amp.png', 'text' => 'Amp'],
    ['num' => 200, 'image' => 'bobomb.png', 'text' => 'Bob-omb'],
    ['num' => 240, 'image' => 'boo.png', 'text' => 'Boo'],
    ['num' => 260, 'image' => 'buzzy_beetle.png', 'text' => 'Buzzy Beetle'],
    ['num' => 280, 'image' => 'broozer.png', 'text' => 'Broozer'],
    ['num' => 300, 'image' => 'bulber.png', 'text' => 'Bulber'],
    ['num' => 325, 'image' => 'angrymoon.png', 'text' => 'Angry Moon'],
    ['num' => 350, 'image' => 'angrysun.png', 'text' => 'Angry Sun'],
    ['num' => 375, 'image' => 'blooper.png', 'text' => 'Blooper'],
    ['num' => 400, 'image' => 'blooper_babies.png', 'text' => 'Blooper With Babies'],
    ['num' => 425, 'image' => 'bramball.png', 'text' => 'Bramball'],
    ['num' => 450, 'image' => 'cheep_red.png', 'text' => 'Red Cheep-Cheep'],
    ['num' => 475, 'image' => 'cheep_yellow.png', 'text' => 'Yellow Cheep-Cheep'],
    ['num' => 500, 'image' => 'cheep_green.png', 'text' => 'Green Cheep-Cheep'],
    ['num' => 525, 'image' => 'crow.png', 'text' => 'Crowber'],
    ['num' => 550, 'image' => 'e_switch.png', 'text' => 'Small Switch'],
    ['num' => 575, 'image' => 'e_switch_lg.png', 'text' => 'Big Switch'],
    ['num' => 625, 'image' => 'boomerangbro.png', 'text' => 'Boomerang Bro'],
    ['num' => 650, 'image' => 'hammerbro.png', 'text' => 'Hammer Brother'],
    ['num' => 675, 'image' => 'firebro.png', 'text' => 'Fire Brother'],
    ['num' => 700, 'image' => 'icebro.png', 'text' => 'Ice Brother'],
    ['num' => 725, 'image' => 'sledgebro.png', 'text' => 'Sledge Brother'],
    ['num' => 750, 'image' => 'fishbones.png', 'text' => 'Fish Bone'],
    ['num' => 800, 'image' => 'foo.png', 'text' => 'Foo'],
    ['num' => 850, 'image' => 'fuzzy.png', 'text' => 'Fuzzy'],
    ['num' => 900, 'image' => 'gabon_r.png', 'text' => 'Spike'],
    ['num' => 950, 'image' => 'gabon_d.png', 'text' => 'Stone Spike'],
    ['num' => 1000, 'image' => 'drybones.png', 'text' => 'Dry Bones'],
    ['num' => 1050, 'image' => 'spike_ball.png', 'text' => 'Spike Ball'],
    ['num' => 1125, 'image' => 'ground_piranha.png', 'text' => 'Piranha Plant'],
    ['num' => 1175, 'image' => 'huckit_crab.png', 'text' => 'Huckit Crab'],
    ['num' => 1250, 'image' => 'jellybeam.png', 'text' => 'Jelly Beam'],
    ['num' => 1300, 'image' => 'lakitu.png', 'text' => 'Lakitu'],
    ['num' => 1350, 'image' => 'little_mouser_0.png', 'text' => 'Mouser'],
    ['num' => 1400, 'image' => 'monty_mole.png', 'text' => 'Monty Mole'],
    ['num' => 1450, 'image' => 'rocky_wrench.png', 'text' => 'Rocky Wrench'],
    ['num' => 1500, 'image' => 'podoboo.png', 'text' => 'Podoboo'],
    ['num' => 1550, 'image' => 'porcu_puffer.png', 'text' => 'Porcu Puffer'],
    ['num' => 1650, 'image' => 'redcoinring.png', 'text' => 'Red Coin Ring'],
    ['num' => 1700, 'image' => 'ShyGuy0.png', 'text' => 'Shy Guy'],
    ['num' => 1750, 'image' => 'ShyGuy1.png', 'text' => 'Blue Shy Guy'],
    ['num' => 1800, 'image' => 'ShyGuy3.png', 'text' => 'Yellow Shy Guy'],
    ['num' => 1850, 'image' => 'ShyGuy4.png', 'text' => 'Pink Shy Guy'],
    ['num' => 1900, 'image' => 'ShyGuy5.png', 'text' => 'Green Shy Guy'],
    ['num' => 2000, 'image' => 'bigredguy.png', 'text' => 'Big Red Guy'],
    ['num' => 2100, 'image' => 'samurai_guy.png', 'text' => 'Samurshai'],
    ['num' => 2200, 'image' => 'spiketop.png', 'text' => 'Spike Top'],
    ['num' => 2300, 'image' => 'spiny.png', 'text' => 'Spiny'],
    ['num' => 2400, 'image' => 'spiny_cheep.png', 'text' => 'Spiny Cheep'],
    ['num' => 2500, 'image' => 'starcoin.png', 'text' => 'Star Coin'],
    ['num' => 2600, 'image' => 'swooper.png', 'text' => 'Swooper'],
    ['num' => 2700, 'image' => 'toad.png', 'text' => 'Toad'],
    ['num' => 2800, 'image' => 'topman.png', 'text' => 'Topman'],
    ['num' => 2900, 'image' => 'wiggler.png', 'text' => 'Wiggler'],
    ['num' => 3000, 'image' => 'Larry_Koopa.png', 'text' => 'Larry Koopa'],
    ['num' => 3100, 'image' => 'Roy_Koopa.png', 'text' => 'Roy Koopa'],
    ['num' => 3200, 'image' => 'Lemmy_Koopa.png', 'text' => 'Lemmy Koopa'],
    ['num' => 3300, 'image' => 'Wendy_Koopa.png', 'text' => 'Wendy Koopa'],
    ['num' => 3400, 'image' => 'Iggy_Koopa.png', 'text' => 'Iggy Koopa'],
    ['num' => 3500, 'image' => 'Morton_Koopa.png', 'text' => 'Morton Koopa'],
    ['num' => 3600, 'image' => 'Ludwig_Von_Koopa.png', 'text' => 'Ludwig von Koopa'],
    ['num' => 3700, 'image' => 'Kamek.png', 'text' => 'Kamek'],
    ['num' => 3800, 'image' => 'Bowser.png', 'text' => 'Bowser'],
    ['num' => 3900, 'image' => 'minimario.png', 'text' => 'Mini Mario'],
    ['num' => 4000, 'image' => 'smallmario.png', 'text' => 'Mario'],
    ['num' => 4100, 'image' => 'supermario.png', 'text' => 'Super Mario'],
    ['num' => 4200, 'image' => 'firemario.png', 'text' => 'Fire Mario'],
    ['num' => 4400, 'image' => 'icemario.png', 'text' => 'Ice Mario'],
    ['num' => 4600, 'image' => 'propeller.png', 'text' => 'Propeller Mario'],
    ['num' => 4800, 'image' => 'penguinmario.png', 'text' => 'Penguin Mario'],
    ['num' => 5000, 'image' => 'starmario.png', 'text' => 'Star Mario'],

];
