<?php

// Zelda Ranket from Acmlmboard 2 by Fyxe. Converted from Acmlmboard format to BlargBoard format by AlphaTech
$ranksetNames['zelda'] = 'Zelda';
$ranksetData['zelda'] = [
['num' => 0, 'image' => '', 'text' => 'Non-poster'],
['num' => 1, 'image' => '', 'text' => 'Newcomer'],
['num' => 10, 'image' => 'Octoballoon.gif', 'text' => 'Octoballoon'],
['num' => 20, 'image' => 'Octorok.gif', 'text' => 'Octorok'],
['num' => 30, 'image' => 'Onoff.gif', 'text' => 'Onoff'],
['num' => 40, 'image' => 'Poe.gif', 'text' => 'Poe'],
['num' => 50, 'image' => 'Popo.gif', 'text' => 'Popo'],
['num' => 60, 'image' => 'PurpleLeever.gif', 'text' => 'Purple Leever'],
['num' => 70, 'image' => 'RabbitLink.gif', 'text' => 'Rabit Link'],
['num' => 80, 'image' => 'Rat.gif', 'text' => 'Rat'],
['num' => 90, 'image' => 'Raven.gif', 'text' => 'Raven'],
['num' => 100, 'image' => 'RedMailLink.gif', 'text' => 'Red Mail Link'],
['num' => 110, 'image' => 'RedStalfos.gif', 'text' => 'Red Stalfos'],
['num' => 120, 'image' => 'RedTektite.gif', 'text' => 'Red Tekite'],
['num' => 130, 'image' => 'RedTorosu.gif', 'text' => 'Red Torosu'],
['num' => 140, 'image' => 'Rocklops.gif', 'text' => 'Rocklops'],
['num' => 150, 'image' => 'Ropa.gif', 'text' => 'Ropa'],
['num' => 160, 'image' => 'Rope.gif', 'text' => 'Rope'],
['num' => 170, 'image' => 'SandCrab.gif', 'text' => 'Sand Crab'],
['num' => 180, 'image' => 'Slime.gif', 'text' => 'Slime'],
['num' => 190, 'image' => 'SnapDragon.gif', 'text' => 'Snap Dragon'],
['num' => 200, 'image' => 'Stalfos.gif', 'text' => 'Stalfos'],
['num' => 210, 'image' => 'Sukarurope.gif', 'text' => 'Sukarurope'],
['num' => 220, 'image' => 'Surarok.gif', 'text' => 'Surarok'],
['num' => 230, 'image' => 'Tektite.gif', 'text' => 'Tektite'],
['num' => 240, 'image' => 'Tendoru.gif', 'text' => 'Tendoru'],
['num' => 250, 'image' => 'TheAdventureOfLink.gif', 'text' => 'The Adventure of Link'],
['num' => 260, 'image' => 'Torosu.gif', 'text' => 'Torosu'],
['num' => 270, 'image' => 'Vire.gif', 'text' => 'Vire'],
['num' => 280, 'image' => 'Vitreous.gif', 'text' => 'Vitreous'],
['num' => 290, 'image' => 'YellowStalfos.gif', 'text' => 'Yellow Stalfos'],
['num' => 300, 'image' => 'Zelda.gif', 'text' => 'Zelda'],
['num' => 310, 'image' => 'Zirro.gif', 'text' => 'Zirro'],
['num' => 320, 'image' => 'Zora.gif', 'text' => 'Zora'],
];
