<?php

// Kirby Ranket from Acmlmboard 2 by YoshiDude. Converted from Acmlmboard format to BlargBoard format by AlphaTech
$ranksetNames['kirby'] = 'Kirby';
$ranksetData['kirby'] = [
['num' => 0, 'image' => '', 'text' => 'Non-poster'],
['num' => 5, 'image' => 'acro.gif', 'text' => 'Acro'],
['num' => 10, 'image' => 'biospark.gif', 'text' => 'BioSpark'],
['num' => 15, 'image' => 'birdon.gif', 'text' => 'Birdon'],
['num' => 20, 'image' => 'bladeknight.gif', 'text' => 'Blade Knight'],
['num' => 25, 'image' => 'blipper.gif', 'text' => 'Blipper'],
['num' => 30, 'image' => 'bobo.gif', 'text' => 'Bobo'],
['num' => 35, 'image' => 'boboo.gif', 'text' => 'Boboo'],
['num' => 40, 'image' => 'bomber.gif', 'text' => 'Bomber'],
['num' => 45, 'image' => 'bonkers.gif', 'text' => 'Bonkers'],
['num' => 50, 'image' => 'bouncy.gif', 'text' => 'Bouncy'],
['num' => 55, 'image' => 'brontoburt.gif', 'text' => 'Bronto Burt'],
['num' => 60, 'image' => 'broomhatter.gif', 'text' => 'Broom Hatter'],
['num' => 65, 'image' => 'bugzzy.gif', 'text' => 'Bugzzy'],
['num' => 70, 'image' => 'burninleo.gif', 'text' => 'Burnin Leo'],
['num' => 75, 'image' => 'butch.gif', 'text' => 'Butch'],
['num' => 80, 'image' => 'cappy.gif', 'text' => 'Cappy'],
['num' => 85, 'image' => 'capsulej.gif', 'text' => 'Capsulej'],
['num' => 90, 'image' => 'captainstitch.gif', 'text' => 'Captain Stitch'],
['num' => 95, 'image' => 'chefkawasaki.gif', 'text' => 'Chef Kawaski'],
['num' => 100, 'image' => 'chilly.gif', 'text' => 'Chilly'],
['num' => 105, 'image' => 'clockwork.gif', 'text' => 'Mr. Tick Tock'],
['num' => 110, 'image' => 'coney.gif', 'text' => 'Coney'],
['num' => 115, 'image' => 'coo.gif', 'text' => 'Coo'],
['num' => 120, 'image' => 'darkmatter.gif', 'text' => 'Dark Matter'],
['num' => 125, 'image' => 'dynababy.gif', 'text' => 'Dyna Baby'],
['num' => 130, 'image' => 'flamemane.gif', 'text' => 'Flamemane'],
['num' => 135, 'image' => 'frosty.gif', 'text' => 'Frosty'],
['num' => 140, 'image' => 'gator.gif', 'text' => 'Gator'],
['num' => 145, 'image' => 'giantwaddledee.gif', 'text' => 'Giant Waddledee'],
['num' => 150, 'image' => 'gim.gif', 'text' => 'Gim'],
['num' => 155, 'image' => 'glunk.gif', 'text' => 'Glunk'],
['num' => 160, 'image' => 'gooey.gif', 'text' => 'Gooey'],
['num' => 165, 'image' => 'gordo.gif', 'text' => 'Gordo'],
['num' => 170, 'image' => 'grizzo.gif', 'text' => 'Grizzo'],
['num' => 175, 'image' => 'gungun.gif', 'text' => 'Gun Gun'],
['num' => 180, 'image' => 'haboki.gif', 'text' => 'Haboki'],
['num' => 185, 'image' => 'jumpershoot.gif', 'text' => 'Jumper Shoot'],
['num' => 190, 'image' => 'kabu.gif', 'text' => 'Kabu'],
['num' => 195, 'image' => 'karateman.gif', 'text' => 'Karate Man'],
['num' => 200, 'image' => 'kine.gif', 'text' => 'Kine'],
['num' => 205, 'image' => 'kingdedede.gif', 'text' => 'King Dedede'],
['num' => 210, 'image' => 'kirbyadventure.gif', 'text' => 'Kirby Adventure'],
['num' => 215, 'image' => 'kirbybreak.gif', 'text' => 'Kirby Break'],
['num' => 220, 'image' => 'kirbydreamland3.gif', 'text' => 'Kirby Dreamland 3'],
['num' => 225, 'image' => 'kirbyplush.gif', 'text' => 'Kirby Plush'],
['num' => 230, 'image' => 'kirbysamurai.gif', 'text' => 'Kirby Samurai'],
['num' => 235, 'image' => 'kirbyship.gif', 'text' => 'Kirby Ship'],
['num' => 240, 'image' => 'kirbysnooze.gif', 'text' => 'Kirby Snooze'],
['num' => 245, 'image' => 'kirbystrut.gif', 'text' => 'Kirby Strut'],
['num' => 250, 'image' => 'kirbywarpstar.gif', 'text' => 'Kirby Warpstar'],
['num' => 255, 'image' => 'knucklejoe.gif', 'text' => 'Knuckle Joe'],
['num' => 260, 'image' => 'kracko.gif', 'text' => 'Kracko'],
['num' => 265, 'image' => 'kruff.gif', 'text' => 'Kruff'],
['num' => 270, 'image' => 'lunarknight.gif', 'text' => 'Lunark Knight'],
['num' => 275, 'image' => 'masher.gif', 'text' => 'Masher'],
['num' => 280, 'image' => 'masterhand.gif', 'text' => 'Master Hand'],
['num' => 285, 'image' => 'metaknight.gif', 'text' => 'Meta Knight'],
['num' => 290, 'image' => 'mrbright.gif', 'text' => 'Mr. Bright'],
['num' => 295, 'image' => 'mrshine.gif', 'text' => 'Mr. Shine'],
['num' => 300, 'image' => 'mumbies.gif', 'text' => 'Mumbies'],
['num' => 310, 'image' => 'noddy.gif', 'text' => 'Noddy'],
['num' => 320, 'image' => 'paintroller.gif', 'text' => 'Paintroller'],
['num' => 330, 'image' => 'panic.gif', 'text' => 'Panic'],
['num' => 340, 'image' => 'parasolwdee.gif', 'text' => 'Parasolwdee'],
['num' => 350, 'image' => 'phanphan.gif', 'text' => 'Phan Phan'],
['num' => 360, 'image' => 'plasmawhisp.gif', 'text' => 'Plasma Whisp'],
['num' => 370, 'image' => 'poppybros.gif', 'text' => 'Poppy Bros'],
['num' => 380, 'image' => 'poppybrossr.gif', 'text' => 'Poppy Brossr'],
['num' => 390, 'image' => 'rick.gif', 'text' => 'Rick'],
['num' => 400, 'image' => 'rocky.gif', 'text' => 'Rocky'],
['num' => 410, 'image' => 'scarfy.gif', 'text' => 'Scarfy'],
['num' => 420, 'image' => 'scarfyprovoked.gif', 'text' => 'Scarfy Provoked'],
['num' => 430, 'image' => 'simirror.gif', 'text' => 'Simirror'],
['num' => 440, 'image' => 'sirkibble.gif', 'text' => 'Sir Kibble'],
['num' => 450, 'image' => 'sparky.gif', 'text' => 'Sparky'],
['num' => 460, 'image' => 'squishy.gif', 'text' => 'Squishy'],
['num' => 470, 'image' => 'starorb.gif', 'text' => 'Star Orb'],
['num' => 480, 'image' => 'stave.gif', 'text' => 'Stave'],
['num' => 490, 'image' => 'tac.gif', 'text' => 'Tac'],
['num' => 500, 'image' => 'togezo.gif', 'text' => 'Togezo'],
['num' => 510, 'image' => 'tooky.gif', 'text' => 'Tooky'],
['num' => 520, 'image' => 'tosstortoise.gif', 'text' => 'Toss Tortoise'],
['num' => 530, 'image' => 'tweet.gif', 'text' => 'Tweet'],
['num' => 540, 'image' => 'twister.gif', 'text' => 'Twister'],
['num' => 550, 'image' => 'ufo.gif', 'text' => 'UFO'],
['num' => 560, 'image' => 'waddledee.gif', 'text' => 'Waddledee'],
['num' => 570, 'image' => 'waddledoo.gif', 'text' => 'Waddledoo'],
['num' => 580, 'image' => 'walkie.gif', 'text' => 'Walkie'],
['num' => 590, 'image' => 'wheeliebig.gif', 'text' => 'Wheelie Big'],
['num' => 600, 'image' => 'wheelierider.gif', 'text' => 'Wheelie Rider'],
['num' => 700, 'image' => 'whispywoods.gif', 'text' => 'Whispy Woods'],
];
