<?php

$ranksetNames['minecraft'] = 'Minecraft';

$ranksetData['minecraft'] = [
    ['num' => 0, 'image' => '', 'text' => 'Non-poster'],
    ['num' => 1, 'image' => '', 'text' => 'Newcomer'],
    ['num' => 10, 'image' => 'dirt.png', 'text' => 'Dirt'],
    ['num' => 20, 'image' => 'grass.png', 'text' => 'Grass'],
    ['num' => 35, 'image' => 'wood.png', 'text' => 'Wood'],
    ['num' => 50, 'image' => 'planks.png', 'text' => 'Planks'],
    ['num' => 65, 'image' => 'stone.png', 'text' => 'Stone'],
    ['num' => 80, 'image' => 'cobble.png', 'text' => 'Cobble'],
    ['num' => 100, 'image' => 'mossy.png', 'text' => 'Mossy Cobble'],
    ['num' => 120, 'image' => 'brick.png', 'text' => 'Brick'],
    ['num' => 140, 'image' => 'bedrock.png', 'text' => 'Bedrock'],
    ['num' => 160, 'image' => 'coal.png', 'text' => 'Coal'],
    ['num' => 180, 'image' => 'iron.png', 'text' => 'Iron'],
    ['num' => 200, 'image' => 'lapis.png', 'text' => 'Lapis Lazuli'],
    ['num' => 225, 'image' => 'gold.png', 'text' => 'Gold'],
    ['num' => 250, 'image' => 'diamond.png', 'text' => 'Diamond'],
    ['num' => 275, 'image' => 'redstone.png', 'text' => 'Redstone'],
    ['num' => 300, 'image' => 'emerald.png', 'text' => 'Emerald'],
    ['num' => 325, 'image' => 'chicken.png', 'text' => 'Chicken'],
    ['num' => 350, 'image' => 'squid.png', 'text' => 'Squid'],
    ['num' => 375, 'image' => 'pig.png', 'text' => 'Pig'],
    ['num' => 400, 'image' => 'sheep.png', 'text' => 'Sheep'],
    ['num' => 425, 'image' => 'cow.png', 'text' => 'Cow'],
    ['num' => 450, 'image' => 'silver.png', 'text' => 'Silverfish'],
    ['num' => 475, 'image' => 'wolf.png', 'text' => 'Wolf'],
    ['num' => 500, 'image' => 'zombie.png', 'text' => 'Zombie'],
    ['num' => 525, 'image' => 'skeleton.png', 'text' => 'Skeleton'],
    ['num' => 550, 'image' => 'creeper.png', 'text' => 'Creeper'],
    ['num' => 575, 'image' => 'villager.png', 'text' => 'Villager'],
    ['num' => 600, 'image' => 'steve.png', 'text' => 'Steve'],
];
