<?php

$ranksetNames['PokemonGenIV'] = 'Pokemon Gen IV';

$ranksetData['PokemonGenIV'] = [
['num' => 0, 'image' => '', 'text' => 'Non-Poster'],
['num' => 5, 'image' => '001.png', 'text' => 'Breloom'],
['num' => 10, 'image' => '002.png', 'text' => 'Lanturn'],
['num' => 15, 'image' => '003.png', 'text' => 'Mr. Mime'],
['num' => 20, 'image' => '004.png', 'text' => 'Dodrio'],
['num' => 25, 'image' => '005.png', 'text' => 'Absol'],
['num' => 30, 'image' => '006.png', 'text' => 'Stantler'],
['num' => 35, 'image' => '007.png', 'text' => 'Skarmory'],
['num' => 40, 'image' => '008.png', 'text' => 'Mantine'],
['num' => 45, 'image' => '009.png', 'text' => 'Forretress'],
['num' => 50, 'image' => '010.png', 'text' => 'Magneton'],
['num' => 55, 'image' => '011.png', 'text' => 'Swalot'],
['num' => 60, 'image' => '012.png', 'text' => 'Crawdaunt'],
['num' => 65, 'image' => '013.png', 'text' => 'Whiscash'],
['num' => 70, 'image' => '014.png', 'text' => 'Pidgeot'],
['num' => 75, 'image' => '015.png', 'text' => 'Grumpig'],
['num' => 80, 'image' => '016.png', 'text' => 'Torkoal'],
['num' => 85, 'image' => '017.png', 'text' => 'Xatu'],
['num' => 90, 'image' => '018.png', 'text' => 'Clefable'],
['num' => 95, 'image' => '019.png', 'text' => 'Vespiquen'],
['num' => 100, 'image' => '020.png', 'text' => 'Hariyama'],
['num' => 105, 'image' => '021.png', 'text' => 'Gastrodon'],
['num' => 110, 'image' => '022.png', 'text' => 'Staraptor'],
['num' => 110, 'image' => '023.png', 'text' => 'Cacturne'],
['num' => 115, 'image' => '024.png', 'text' => 'Manectric'],
['num' => 120, 'image' => '025.png', 'text' => 'Kingler'],
['num' => 125, 'image' => '026.png', 'text' => 'Dewgong'],
['num' => 130, 'image' => '027.png', 'text' => 'Raichu'],
['num' => 135, 'image' => '028.png', 'text' => 'Skuntank'],
['num' => 140, 'image' => '029.png', 'text' => 'Phione'],
['num' => 145, 'image' => '030.png', 'text' => 'Froslass'],
['num' => 150, 'image' => '031.png', 'text' => 'Lopunny'],
['num' => 155, 'image' => '032.png', 'text' => 'Glalie'],
['num' => 160, 'image' => '033.png', 'text' => 'Exploud'],
['num' => 165, 'image' => '034.png', 'text' => 'Shiftry'],
['num' => 170, 'image' => '035.png', 'text' => 'Ludicolo'],
['num' => 175, 'image' => '036.png', 'text' => 'Octillery'],
['num' => 180, 'image' => '182.png', 'text' => 'Bellossom'],
['num' => 185, 'image' => '037.png', 'text' => 'Electrode'],
['num' => 190, 'image' => '038.png', 'text' => 'Victreebel'],
['num' => 195, 'image' => '039.png', 'text' => 'Vileplume'],
['num' => 200, 'image' => '040.png', 'text' => 'Ambipom'],
['num' => 205, 'image' => '041.png', 'text' => 'Hypno'],
['num' => 210, 'image' => '042.png', 'text' => 'Spiritomb'],
['num' => 215, 'image' => '043.png', 'text' => 'Relicanth'],

];
// need to do about a few hundred more (http://www.serebii.net/pokedex-dp/stat/all.shtml) <-- the link to website for sprites.
// stopped at Gorebyss
